### ISSUE TITLE
Repeated full-library downloads when pulling down on items list

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-android#104]
Every time, it requests `/users/[…]/settings?since=2888` followed by the same `items?itemKey=` requests, and it stays at 2888 each time.

Oddly, this is what's logged: D1975856021

This shows the 2888, but it doesn't show any of the actual sync requests.

**Comment by Dima-Android** [comment]
@dstillman Is this issue still present? I think we resolved it recently.

**Comment by dstillman** [comment]
Yes, I think it was fixed in https://github.com/zotero/zotero-android/commit/55c69efa33a346a652ce628ed9ad68e2f68f4adc.
