### ISSUE TITLE
No CI builds or releases

### ISSUE THREAD

**Issue by KorigamiK** [zotero/zotero-android#110]
The Play store beta is mostly full and many of us are unable to use the Play store.

It should be simple enough to create a CI workflow and upload the artifacts as a pre-release build on GitHub.

**Comment by dstillman** [comment]
The beta is full because we set a limit on the number of initial testers. You're welcome to build the app from source, but we're obviously not going to go out of our way to provide a build outside the official beta at this time.

**Comment by KorigamiK** [comment]
> You're welcome to build the app from source

I would gladly build from source if the beta is closed for now, however the psppdfit key is not something that anyone has trivially nor is a signing key for a release build. 

It would be great if the team could consider members outside the beta program to test the app since it's quite essential to what zotero offers on Android.

**Comment by ShrirajHegde** [comment]
@dstillman can't you just upload the built APK as an artifact in GitHub workflow?

It's already built in the workflow and people can grab them easily and test the latest commit.

**Comment by northword** [comment]
I created a repository to compile Zotero Android from source.

https://github.com/northword/zotero-android-nightly-build

Note: The apk released in this repository has not been validated and tested by the official team, so it may have serious problems and is FOR TEST ONLY, NOT FOR PRODUCTION!
