### ISSUE TITLE
Don't use "isbn" to refer to generic identifier functionality

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-android#131]
For example: https://github.com/zotero/zotero-android/blob/44382a57d053066315f231c690357b0bef98f207/app/src/main/java/org/zotero/android/uicomponents/addbyidentifier/AddByIdentifierScreen.kt#L85

ISBNs are just one of many supported identifiers.

**Comment by Dima-Android** [comment]
Addressed as part of this commit 8b9836cc85dbadd3b299a769639a9420aca63793
