### ISSUE TITLE
Hide PSPDFKit Strikethrough and Underline in text-selection popup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-android#137]
https://forums.zotero.org/discussion/comment/465957/#Comment_465957

**Comment by dstillman** [comment]
We should do this soon if possible, since it's effectively a data-loss bug.

**Comment by Dima-Android** [comment]
Was not able to reproduce it on any of my PDFs but in recent PSPDFKIT changelogs I found this:
"Fixes an issue where text highlights were split when there was a tiny gap in a sentence"
"Fixes an issue where text blocks were split when encountering two or more narrow characters."

**Comment by Dima-Android** [comment]
Not 100% sure but I think there is no way to remove specific options from text-selection popup. Only to show and hide toolbar in its entirety. So I’m hiding it.

**Comment by dstillman** [comment]
Hmm, but this toolbar is the only way we have a functional multiline highlight. Can we add that back ourselves?
