### ISSUE TITLE
Hide status bar in reader full-screen mode?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-android#140]
https://forums.zotero.org/discussion/115813/android-fullscreen

Not sure if it's possible here, but we hide the status bar on iOS.

**Comment by atnoir** [comment]
@dstillman please make Samsung's taskbar (a [native feature](https://developer.android.com/about/versions/13/features/large-screens) in Android tablet) hidden as well in the reader full-screen mode. thanks.
