### ISSUE TITLE
Two slashes used in WebDAV URL

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-android#149]
https://forums.zotero.org/discussion/comment/470475/#Comment_470475

```
(+0000008): [DEBUG] --> GET https://dav.jianguoyun.com/dav/zotero//nonexistent.prop
```

I assume this is what's causing the 400.

**Comment by Dima-Android** [comment]
Should be fixed by this commit 677a3a609f22c3e1da113ad898474c4d783132b9
