### ISSUE TITLE
Https error: trust anchor for certification path not found

### ISSUE THREAD

**Issue by Hemingway2003** [zotero/zotero-android#169]
While I change the sync way to webdav, input the correct username and password (I checked them on my another phone, it's ok)
I click the `Verify Server`, the app warned to me: 
```
Https error: trust anchor for certification path not found
```
I changed the https to http, the app warned:
```
Due to Android restrictions, HTTP can only be used when connecting to a .local hostname
```

**Comment by dstillman** [comment]
https://github.com/zotero/zotero-android/blob/master/CONTRIBUTING.md
