### ISSUE TITLE
Show items from subcollections

### ISSUE THREAD

**Issue by UrbanJoker** [zotero/zotero-android#179]
**READ THIS BEFORE CREATING AN ISSUE**

Zotero does not use GitHub Issues for bug reports or feature requests.

Please post all such requests to the Zotero Forums at https://forums.zotero.org, where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

Development questions involving code, APIs, or other technical topics can be posted to the zotero-dev mailing list at http://groups.google.com/group/zotero-dev.

See https://www.zotero.org/support/zotero_support for more information on how Zotero support works.

**Comment by UrbanJoker** [comment]
The Zotero Android app does not display items from sub-collections, and there is no setting to enable this feature, as in the PC counterpart. This is a basic app feature that should be considered.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero-android/blob/master/CONTRIBUTING.md
