### ISSUE TITLE
How can I build a release version?

### ISSUE THREAD

**Issue by znsoftm** [zotero/zotero-android#180]
Building zotero from the source has been done but except release edition.  There needs a trial key for pdf reader control. So how can I build a release version of zotero from scratch?

Where do I  put a pdf key file?

**Comment by dstillman** [comment]
I'm not sure what you're asking. We build the "release" version with the PDF reader key that we have a license for. If you build the app yourself, the reader will be in trial mode.

**Comment by znsoftm** [comment]
if I have a license key, where should I put it in the directory tree ?
