### ISSUE TITLE
For Note, Underline, Highlight,Square and Freestyle annotations color and font size are not changed on mobile phone and are changed but not saved on Tablet. 

### ISSUE THREAD

**Issue by Dima-Android** [zotero/zotero-android#186]
When color and font size are changed for an existing annotation via helper screens the results of those changes appear to get ignored.
This bug turns out to have been present for a while and is unrelated to recent PdfScreen improvements.

**Comment by foss-** [comment]
This sounds like it explans why color changes were not reflected in desktop app:
https://forums.zotero.org/discussion/118320/android-incorrect-colors-for-draw-annotations#latest
