### ISSUE TITLE
F-droid / .apk build as a release on github

### ISSUE THREAD

**Issue by RichardJActon** [zotero/zotero-android#198]
Hi My desktop Zotero just updated to v7, thought it was awesome and went looking for the release notes and to generally check-in on Zotero development for the first time in a little while. Discovered through the forum that this app is being worked on and in Beta - really looking forward to trying it out.

I don't use the play store and was wondering if there are plans to have an F-droid release and/or release `.apk`s directly via the github project so it can be installed manually or with tools like [Obtanium](https://obtainium.imranr.dev/)?

**Comment by dstillman** [comment]
We plan to release an APK once the app is out of beta.

**Comment by UlyssesZh** [comment]
Would you like the community to package the app on F-Droid?

**Comment by NiuBlibing** [comment]
@dstillman Any news?

**Comment by guyjax** [comment]
great news APK published, thanks @dstillman https://www.zotero.org/download/android/
