### ISSUE TITLE
Confirm back action when modifying item metadata

### ISSUE THREAD

**Issue by fcheslack** [zotero/zotero-android#58]
Similar to notes, it's possible to lose work when backing out of editing item metadata. There's not as much potential for lost work here, but if possible I think we should have a confirmation when using the back action (rather than the "Cancel" button) to leave the edit info pane if there are modifications.

**Comment by Dima-Android** [comment]
The Item Details screen now has similar flow as on iOS. Cancel/Save buttons no longer appear after you hit the Edit button. Just the Done button. And also leaving this screen with Android’s Hardware back button will not lose progress as the data is being saved immediately as user is typing into the fields.
