### ISSUE TITLE
Some items don't have their pdf attachment show up on allitems screen

### ISSUE THREAD

**Issue by yexingsha** [zotero/zotero-android#81]
For example, in the screenshot below, all these items with snapshots actually have pdf as their default attachment:

<img src=https://github.com/zotero/zotero-android/assets/57771795/45129947-e636-4514-8072-3dc357863300 width="360">

Which means the only way to access their pdf attachment is via itemdetails screen:

<img src=https://github.com/zotero/zotero-android/assets/57771795/e4b55200-6631-4455-8c32-7ad901fe94f3 width="360">

From what I can see, this seems to affect items with both pdf attachment and snapshot.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/111351/android-attachment-type-bug-in-list-view

**Comment by dstillman** [comment]
This is the logic:

https://github.com/zotero/zotero/blob/a23b5310e6fb3b21896bd50885512b78a53088b1/chrome/content/zotero/xpcom/data/item.js#L3693-L3695

And if no attachment, we fall back to URL, followed by DOI.
